
cc_library(
    name = "demp",
    srcs = glob([
        "grpc_demo.cpp",
    ]),
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_grpc_grpc//:grpc++",
        "@com_google_protobuf//:protobuf",
    ],
)
