package(default_visibility=['//aios/util:__subpackages__'])
cc_library(
    name='json_testlib',
    testonly=True,
    srcs=['JsonTestUtil.cpp'],
    hdrs=['JsonTestUtil.h'],
    include_prefix='util/legacy/test',
    visibility=['//visibility:public'],
    deps=['//aios/util:json_helper', '//aios/unittest_framework:unittest_lib']
)
